settings:
  application:
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: "8000"
    readtimeout: 1
    writertimeout: 2
    domain: localhost:8000
    ishttps: false
  ssl:
    key: keystring
    pem: temp/pem.pem
  database:
    dbtype: mysql
    host: 192.168.10.99
    name: goadmindb
    password: Itzler.666
    port: 3306
    username: root
  jwt:
    secret: go-admin
    timeout: 3600
  log:
    dir: temp/logs
